# Generated by Django 4.0.5 on 2022-07-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('container', models.TextField()),
                ('anchorNode', models.TextField()),
                ('anchorOffset', models.TextField()),
                ('focusNode', models.TextField()),
                ('focusOffset', models.TextField()),
                ('note', models.TextField(null=True)),
            ],
        ),
    ]
