# Generated by Django 4.0.5 on 2022-07-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='anchorOffset',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='focusOffset',
            field=models.IntegerField(),
        ),
    ]
