# Generated by Django 4.0.5 on 2022-08-11 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_owner_alter_document_created_date_and_more'),
        ('highlight', '0002_alter_highlight_anchoroffset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
