# Generated by Django 4.0.5 on 2022-08-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_document_folder_alter_document_owner_and_more'),
        ('highlight', '0003_highlight_document_alter_highlight_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
            preserve_default=False,
        ),
    ]
