# Generated by Django 4.0.5 on 2022-08-11 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='privacy',
            field=models.CharField(choices=[('pr', 'Private'), ('pu', 'Public')], default='pr', max_length=2),
        ),
        migrations.AlterField(
            model_name='document',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('ar', 'Article')], default='ar', max_length=2),
        ),
        migrations.AlterField(
            model_name='document',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(),
        ),
    ]
