# Generated by Django 4.0.5 on 2022-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_delete_tag_delete_taggeddocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('use_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.ManyToManyField(null=True, to='documents.tag'),
        ),
    ]
