# Generated by Django 4.0.5 on 2022-08-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_tag_document_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tag',
            field=models.ManyToManyField(to='documents.tag'),
        ),
    ]
