# Generated by Django 4.0.5 on 2022-08-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='tag',
            new_name='tags',
        ),
    ]
