# Generated by Django 4.0.5 on 2022-08-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_docrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='rating',
        ),
    ]
